
package com.cybersource.schemas.transaction.data.transactionprocessor;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import com.cybersource.schemas.transaction.data.ObjectFactory;
import com.cybersource.schemas.transaction.data.ReplyMessage;
import com.cybersource.schemas.transaction.data.RequestMessage;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ITransactionProcessor", targetNamespace = "urn:schemas-cybersource-com:transaction-data:TransactionProcessor")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ITransactionProcessor {


    /**
     * 
     * @param input
     * @return
     *     returns com.cybersource.schemas.transaction_data_1.ReplyMessage
     */
    @WebMethod(action = "runTransaction")
    @WebResult(name = "replyMessage", targetNamespace = "urn:schemas-cybersource-com:transaction-data-1.159", partName = "result")
    public ReplyMessage runTransaction(
        @WebParam(name = "requestMessage", targetNamespace = "urn:schemas-cybersource-com:transaction-data-1.159", partName = "input")
        RequestMessage input);

}
